services:
  app:
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FCM_SERVICE_ACCOUNT_KEY_PATH=/app/firebase-admin.json
    volumes:
      - /opt/mymate/firebase-admin.json:/app/firebase-admin.json:ro

