services:
  redis:
    image: redis:7.0
    ports:
      - '6379:6379'
    networks:
      - mymate-network

  app:
    build: .
    env_file:
      - .env.prod
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - '8080:8080'  # API는 외부에 열어야 하니까 이건 OK
    depends_on:
      - redis
    networks:
      - mymate-network
    volumes:
      - ./firebase-admin.json:/app/firebase-admin.json:ro

networks:
  mymate-network:
    driver: bridge
