services:
  redis:
    image: redis:7.0
    networks:
      - mymate-network

  app:
    image: ${DOCKERHUB_USERNAME}/mymate:latest
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - '8080:8080'  # API는 외부에 열어야 하니까 이건 OK
    depends_on:
      - redis
    networks:
      - mymate-network

networks:
  mymate-network:
    driver: bridge
