oauth:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    playground-client-id: ${GOOGLE_PLAYGROUND_CLIENT_ID}
    
  kakao:
    client-id: ${KAKAO_REST_API_KEY}
    
  naver:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}