oauth:
  google:
    client-id: ${GOOGLE_CLIENT_ID:temp-google-client-id}
    playground-client-id: ${GOOGLE_PLAYGROUND_CLIENT_ID:temp-playground-client-id}
    
  kakao:
    client-id: ${KAKAO_REST_API_KEY:temp-kakao-key}
    
  naver:
    client-id: ${NAVER_CLIENT_ID:temp-naver-client-id}
    client-secret: ${NAVER_CLIENT_SECRET:temp-naver-secret}