token:
  store:
    impl: lua
  refresh:
    ttl-seconds: 1209600
  hmac-secret: ${REFRESH_HMAC_SECRET:dev-change-me-please}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}  # 기본 dev
    include: oauth
    # 필요시 password, timeout 등 추가 가능
  jackson:
    serialization:
      write-dates-as-timestamps: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}



# 공통 설정이 있다면 여기에
jwt:
  secret: your-super-secret-key-that-should-be-long-and-secure

solapi:
  api-key: ${SOLAPI_API_KEY:}
  api-secret: ${SOLAPI_API_SECRET:}
  default-from: ${SOLAPI_DEFAULT_FROM:}

